name: lint code

on:
  push:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@9a9194f87191a7e9055e3e9b95b8cfb13023bb08
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: install
      run: npm i
    - name: lint
      run: npm run lint