name: lint code

on:
  push:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@b80ff79f1755d06ba70441c368a6fe801f5f3a62
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: install
      run: npm i
    - name: lint
      run: run lint